//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diets
    {
        public int idDiet { get; set; }
        public int idFeed { get; set; }
        public int idCat { get; set; }
        public int QuantityMonth { get; set; }
    
        public virtual Cats Cats { get; set; }
        public virtual FeedCat FeedCat { get; set; }
    }
}
