//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MukhinaTestBaseEntities1 : DbContext
    {
        public MukhinaTestBaseEntities1()
            : base("name=MukhinaTestBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cats> Cats { get; set; }
        public virtual DbSet<Diets> Diets { get; set; }
        public virtual DbSet<FeedCat> FeedCat { get; set; }
        public virtual DbSet<GenderTable> GenderTable { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<Traits> Traits { get; set; }
        public virtual DbSet<TraitsCats> TraitsCats { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
