//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IDUser { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Login { get; set; }
        public int Password { get; set; }
        public int IDGender { get; set; }
        public int IDRole { get; set; }
    
        public virtual GenderTable GenderTable { get; set; }
        public virtual RoleTable RoleTable { get; set; }
    }
}
